project_id = "corridorshare"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
major_version = 15

[studio]
enabled = true

[auth]
enabled = true
site_url = "https://corridorshare-tan.vercel.app"
additional_redirect_urls = ["http://localhost:3000", "https://corridorshare-tan.vercel.app", "https://corridorshare-fahmid-hasans-projects.vercel.app"]

